### PR TITLE
implement `immutable_registers` method

### PR DESCRIPTION
**Pull request by omarandlorraine**
This commit just puts in the `immutable_registers` method

### CODE REVIEW

**Comment by ivanizag** [comment]
That was easy.

Thank you!

**Comment by omarandlorraine** [comment]
>Thank you!

You're welcome!

Do you know what will happen with version bump, publishing to crates.io, etc.? I guess you have a release cycle or some such?

**Comment by ivanizag** [comment]
I can build a new version and publish the crate. But I am right now on a business trip, it may take me a couple of days.

**Comment by omarandlorraine** [comment]
> it may take me a couple of days.

No problem, thanks for your help

**Comment by ivanizag** [comment]
It's published now as v0.3.7.
Thank you for your contribution.

**Pull request merged**
